### PR TITLE
About Page Successfully Created

### PR DESCRIPTION
**Pull request by avezqureshi14**
About Page Successfully Created

### CODE REVIEW

**Comment by jeetsavsani1173** [comment]
can you please made PR in same branch @avezqureshi14  ?

**Comment by avezqureshi14** [comment]
@jeetsavsani1173  Do you mean in main branch ?

**Comment by jeetsavsani1173** [comment]
Yes @avezqureshi14

**Comment by avezqureshi14** [comment]
Bro @jeetsavsani1173 how can i merge in your main branch 🤔, When try to merge it says I don to have access rights to that branch

**Pull request merged**
