### PR TITLE
created signup(Register) Form

### PR DESCRIPTION
**Pull request by Gulshan-11**

### CODE REVIEW

**Comment by Gulshan-11** [comment]
Created signup form 
closes #7

**Comment by Gulshan-11** [comment]
Hey @jeetsavsani1173 lemme know if there are any changes to be made

**Comment by jeetsavsani1173** [comment]
Great Work!! <br> Acually @Gulshan-11 You have made great UI but it is not Responsive try to give responsive design and you can also work on SignIn form than pull your request <br> and yaa one more thing when user click on any button there is one popUp type thing apear if you know how to do you can good to go and you can take refrence from https://novoresume.com/page/o/auth-required?pageAuthDesired=/editor this website

**Comment by Gulshan-11** [comment]
> Great Work!! <br> Acually @Gulshan-11 You have made great UI but it is not Responsive try to give responsive design and you can also work on SignIn form than pull your request <br> and yaa one more thing when user click on any button there is one popUp type thing apear if you know how to do you can good to go and you can take refrence from https://novoresume.com/page/o/auth-required?pageAuthDesired=/editor this website

Sure @jeetsavsani1173 
I wil work on sign in and make it responsive. 
And about the pop up, I will try to do that.

**Pull request merged**
